Proyecto_Web/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('servicios/', include('servicios.urls')),

    path('blog/', include('blog.urls')),

    path('contacto/', include('contacto.urls'),),
    
    path('tienda/', include('tienda.urls'),),
    
    path('carro/', include('carro.urls'),),

    path('autenticacion/', include('autenticacion.urls'),),

    path('pedidos/', include('pedidos.urls'),),

    path('', include('Proyecto_Web_App.urls')),
]

blog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.blog, name="Blog"),
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria"),
]

carro/urls.py
"""Views tienda's app."""
from django.urls import path
from .import views

app_name="carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("vaciar/", views.vaciar_productos, name="vaciar"),
]

tienda/urls.py
"""Views tienda's app."""
from django.urls import path
from .import views

urlpatterns = [
    path('', views.tienda, name="Tienda"),
]

tienda/models.py
"""Models of 'tienda' app."""
from django.db import models    

# Create your models here.

class CategoriaProd(models.Model):
    """Category of the products."""
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="categoriaProd"
        verbose_name_plural="categoriasProd"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    """Producto model."""
    nombre=models.CharField(max_length=50)
    categoria=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
    precio=models.FloatField() 
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

carro/views.py
"""Views of the app 'tienda'"""
from django.shortcuts import redirect
from tienda.models import Producto
from .carro import Carro

# Create your views here.

def agregar_producto(request, producto_id):
    """View to add a new products to shopping cart."""
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("Tienda")

def eliminar_producto(request, producto_id):
    """View to delete products to shopping cart."""
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("Tienda")

def restar_producto(request, producto_id):
    """View to subtract products to shopping cart."""
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar(producto=producto)
    return redirect("Tienda")

def vaciar_productos(request):
    """View to empty the shopping cart."""
    carro=Carro(request)
    carro.vaciar_carro()
    return redirect("Tienda")

tienda/views.py
"""The views for the 'tienda' app."""
from django.shortcuts import render
from .models import Producto
# Create your views here.

def tienda(request):
    """A view that render 'tienda' web page."""
    productos=Producto.objects.all()
    return render(request, "tienda/tienda.html", {"productos":productos})

tienda/templates/carro/widget.html
<table class="table table-dark table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro compras
            </th>
        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Parcial</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success"> + </a>
                       
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success"> - </a><br/>
                        
                        {{value.precio}} Bs
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos.
                    </div>
                </td>
            </tr>        
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{importe_total_carro}} Bs
            </td>
        </tr>
        
        {% if request.session.carro.items %}
            <tr>
                <td colspan="3" style="text-align: center;">
                    <!-- <a href="../pedidos" class="btn btn-success"> -->
                    <a href="{% url 'procesar_pedido' %}" class="btn btn-success">
                        Realizar pedido
                    </a>                
                </td>
            </tr>
        {% endif %}
        
    </tfoot>
</table>